[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["lib"]

# Compiler Settings
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true 

# Permissions
fs_permissions = [{ access = "read", path = "./" }]

# Reporting
gas_reports = ["*"]

# Metadata
metadata = true
metadata_hash = "none" 
use_literal_content = true 

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"


remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]
